image:
- Ubuntu
- Visual Studio 2017

stack: jdk 8
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  BITESTS_ARTIFACTORY_URL:
    secure: LzTBwdfXRqjkYMtbOoW8z5Mk5uWCcyyUkg6uYON3mXNCXhz9BbaYuWBypriCHbHy
  BITESTS_ARTIFACTORY_USERNAME:
    secure: LSyETgk50Lwkg7eGUXlgQA==
  BITESTS_ARTIFACTORY_PASSWORD:
    secure: mziQvsWujgLfKsB6m5BH6Q==
  BITESTS_ARTIFACTORY_REPO:
    secure: 9SOPPlF7Tv6TY7k+ZxgRDA==

test_script:
- sh: ./gradlew clean test
- cmd: gradlew.bat clean test

build: off