stack: jdk 8, node 8
skip_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

  BITESTS_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  BITESTS_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  BITESTS_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  BITESTS_ARTIFACTORY_REPO:
    secure: Xf371RQAxCTMn/S7NdmV8g==

test_script:
  - sh: ./gradlew clean test
  - cmd: gradlew.bat clean test

build: off